name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 16
        uses: actions/setup-java@v2
        with:
          java-version: 16

      - name: Update Gradle wrapper
        run: ./gradlew wrapper --gradle-version=7.2.1
        working-directory: .

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace
        working-directory: .
