name: Build Android Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.12
          distribution: 'adopt'
      - name: Set executable permissions for Gradle wrapper
        run: chmod +x ./gradlew # set executable permissions for Gradle wrapper
      - name: Build with Gradle
        run: ./gradlew assembleDebug
