name: Build Android Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.2 # Updated version that supports Node.js 16
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.2 # Updated version that supports Node.js 16
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew assembleDebug
